### ISSUE TITLE
Consistent field naming system

### ISSUE THREAD

**Issue by adamcharnock** [adamcharnock/mate3#3]
## The problem

Field are currently named and referenced very inconsistently. For example:

### `mate3`

`mate3` output humanifys device names, and displays field names nested below:

<img width="407" alt="Screenshot 2020-03-02 at 23 47 21" src="https://user-images.githubusercontent.com/138215/75728588-2caa2800-5ce0-11ea-98fb-8ee4db5898d2.png">

### `mate3_write`

`mate3_write` uses a `.` notation:

<img width="813" alt="Screenshot 2020-03-02 at 23 48 27" src="https://user-images.githubusercontent.com/138215/75728637-5ebb8a00-5ce0-11ea-95d2-1927bb7f7792.png">

### API

The programmatic API requires one to reference the field via the Parser class:

```python
from mate3.parsers import ChargeControllerParser

values = client.get_values(
    ChargeControllerParser.battery_current, 
    ChargeControllerParser.battery_voltage
)
```

## The solution

The solution needs to:

* Be readable when printed to the terminal
* Be useable as python code
* be able to identify a specific device, even when multiple of the same device are connected.

I therefore propose the following:

```
client.{device_name_as_plural}[{device_number}].{field_name}
```

Example:

```python
client.charge_controllers[0].absorb_volts
```

We can also enhance this further. Currently, for example, `ChargeControllerParser` and `ChargeControllerConfigurationParser` are two separate devices. This doesn't really make conceptual sense. Using the above scheme, this would appear as:

```python
client.charge_controllers[0].field_name
client.charge_controller_configs[0].field_name
```

Instead, this would be nicer:

```python
client.charge_controllers[0].field_name
client.charge_controllers[0].config.field_name
```

Additionally, there can only be one of some devices. These have not port number. For example, `mate3.smtp_account_name`. These cases would be used without the pluralisation, and without the indexing. For example:

```python
client.mate3.smtp_account_name
```

## Tasks

- [x] Move field definitions away from the parser classes
- [ ] Refactor client API to support new scheme
  - [ ] Reading
  - [ ] Writing
- [ ] Support ancillary access via original outback field names
- [ ] Update `mate3` to use this output format (maybe with some nice colours)
- [ ] Update `mate3_write` to use this output format (maybe with some nice colours)
- [ ] Generate markdown document of all fields (include original output field name)

**Comment by adamcharnock** [comment]
Thinking through how to refactor the code. The following are rather duplicated

* The `Device` enum - Stores the device IDs
* The `Parser` classes - Stores information about each field
* The `Structure` classes - Stores values a given device

We still need all this information, but it would be nice to find a better way to represent it.

For example, could we merge this all into one `Block` class? This would need to:

* Store field metadata
* Store values
* Store the device ID

**Comment by kodonnell** [comment]
Are you still working on this @adamcharnock ? I haven't dug into this repo too far, but I like the dynamic generation and such, and may be keen to help as part of my little monitoring side project. 

A question: It sounds like the `ChargeController` is a 'SunSpec Basic Charge Controller' while `ChargeControllerConfiguration` is a 'Vendor Extension for OutBack FM Series Charge Controllers' i.e. just an extension Outback made to add extra things they want. Can we abstract this away so users don't have to worry about the difference, and just deal in `ChargeController` (which can access both basic and config blocks).

**Comment by adamcharnock** [comment]
Hi @kodonnell,

I definitely have a work-in-progress branch at `issues/3`, although I cannot remember how far I got with it. If you want to pick it up and do some more work on it then you are very welcome to.

> Can we abstract this away so users don't have to worry about the difference, and just deal in ChargeController

I think I refer to this in the issue description above. I propose the following format:

```python
client.charge_controllers[0].config.field_name
```

**Comment by kodonnell** [comment]
> I definitely have a work-in-progress branch at issues/3 ...

Sorry, I did have a look at the time, and could only see the master branch - maybe that's a private branch?

> client.charge_controllers[0].config.field_name

I'm proposing dropping the `config` - unless there are conflicting fields (which there shouldn't be as that's the point of the extension - but easy to check) then this makes sense.

**Comment by adamcharnock** [comment]
> I'm proposing dropping the config 

No strong views on this, I'm happy for you to drop the `config`

**Comment by kodonnell** [comment]
Re `config`, I just saw this in the PDF:

> **NOTE**:  OutBack charge controllers have a separate block for status fields and a separate block for command  and control fields. 

That makes sense, but it doesn't seem to be true as there are a lot of status (i.e. read-only) fields on the configuration block,. And, as a user, I don't want to have to remember which field goes on which block. So I probably will drop the `config`.

**Comment by kodonnell** [comment]
Should we close this @adamcharnock ? I'm not sure it's fully implemented, but I think a lot of it was covered by #6

**Comment by adamcharnock** [comment]
Sure, happy for you to close it @kodonnell. When I come back to this I may re-open if I want to do some more work on it.

**Comment by kodonnell** [comment]
Awesome - let's do that, especially as I think many of the details have been implemented. I should note that I'm not particularly wed to the current approach - basically, I tried heaps of different methods for naming/accessing things (e.g. `dataclasses` vs `Enum` etc.) and eventually settled on what's here ... though I'm not sure I'll be able to remember why!

The main bug-bears I think I still had were:

1. The model and config being separate. You currently get the config values from a `.config` attribute, but it's confusing, and if we can merge the two (`getattr` etc.) that'd be nicer for the user ... they shouldn't have to worry about the inner workings of how Outback implemented modbus things. That said, I think I spent time on this ... I'm not sure why I didn't implement it (unless there are non-trivial naming collisions?)
2. The enum fields. For now they work, but they could probably be tidied up a bit.
